name: Create Metadata
run-name: Create ${{ inputs.version }} Metadata

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      MAVEN_USER:
        required: false
      MAVEN_PASSWORD:
        required: false
  workflow_dispatch:
    inputs:
      version:
        description: 'Minecraft Version'
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish
        env:
          VERSION: ${{ inputs.version }}
          ORG_GRADLE_PROJECT_MAVEN_URL: ${{ vars.MAVEN_URL }}
          ORG_GRADLE_PROJECT_MAVEN_USER: ${{ secrets.MAVEN_USER }}
          ORG_GRADLE_PROJECT_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publish -PminecraftVersion=$VERSION
